<a href="https://colab.research.google.com/github/mamudurujagadeesh7-cloud/Edukron-DS/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Retail Analytics Assignment

## Business Scenario

You are working as a Data Analyst for **SmartMart Retail Stores**. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

1. `sales_data` — monthly sales revenue generated by each store for different product categories.
2. `cost_data` — total cost incurred by each store for the same product categories.

---

# Part 1: Dataset Creation

```python
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)
```

---

# Part 2: Basic Array Understanding

## Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

* Number of dimensions in `sales_data`
* Shape of `sales_data`
* Total number of values
* Data type of the array
* Memory occupied by the array

---

## Question 2: Store and Category Count

Calculate the following:

* Total number of stores
* Total number of product categories
* Total number of store-category combinations

---

## Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert `sales_data` into:

* `float32`
* `float64`

Compare the memory used by both arrays.

---

# Part 3: Indexing and Data Extraction

## Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

---

## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

---

## Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from `sales_data`.

---

## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

---

## Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

* Furniture sales
* Furniture cost
* Furniture profit

---

## Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

* Groceries
* Clothing
* Furniture

Use array slicing.

---

## Question 10: Selected Store Analysis

Extract sales data for:

* Bengaluru
* Chennai
* Pune

Include only:

* Electronics
* Clothing
* Beauty

Use advanced indexing.

---

# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

---

## Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

```text
Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales
```

---

## Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

---

## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

---

## Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

---

## Question 16: Highest-Selling Store

Identify:

* Index of the store with the highest total sales
* Name of the store
* Total sales generated by that store

Use `np.argmax()`.

---

## Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use `np.argmin()`.

---

## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

---

## Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

---

# Part 5: Cost Analysis

## Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

---

## Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

---

## Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

---

## Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

---

## Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

---

## Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

---

# Part 6: Profit Analysis Using Two Arrays

## Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:

```python
profit_data = sales_data - cost_data
```

Display the complete profit matrix.

---

## Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

---

## Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

---

## Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

Display:

* Store name
* Total sales
* Total cost
* Total profit

---

## Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

---

## Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

---

## Question 32: Least Profitable Category

Find the category with the lowest total profit.

---

## Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

* Profit amount
* Store name
* Product category

Use `np.unravel_index()`.

---

## Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

---

# Part 7: Profit Margin Analysis

## Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:

```python
profit_margin = (profit_data / sales_data) * 100
```

Round the result to two decimal places.

---

## Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

```text
Store Profit Margin =
Total Store Profit / Total Store Sales × 100
```

---

## Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

---

## Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

---

## Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

---

## Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

* Store
* Category
* Sales
* Cost
* Profit
* Profit margin

Use Boolean indexing.

---

# Part 8: Boolean Filtering

## Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

---

## Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

---

## Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

---

## Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use `np.logical_and()`.

---

## Question 45: Premium Performance

A store-category combination is considered premium when:

* Sales are greater than ₹5,00,000
* Profit is greater than ₹1,50,000

Find all premium-performing combinations.

---

## Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

* Sales are below ₹2,50,000
* Profit margin is below 25%

Find all such combinations.

---

## Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

* `"High"` when sales are at least ₹5,00,000
* `"Medium"` when sales are between ₹2,50,000 and ₹4,99,999
* `"Low"` when sales are below ₹2,50,000

Use `np.where()` or `np.select()`.

---

# Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

```python
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
```

## Question 48: Target Comparison

Compare every store’s category sales against `sales_targets`.

Use NumPy broadcasting.

---

## Question 49: Target Achievement Matrix

Create a Boolean array where:

* `True` means the store achieved the category target
* `False` means the store failed to achieve the target

---

## Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

---

## Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

---

## Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

---

## Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use:

```text
Variance = Actual Sales - Target Sales
```

---

## Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

```text
Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100
```

---

## Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

---

## Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use `np.all()`.

---

## Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use `np.any()`.

---

# Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:

```python
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
```

## Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.

---

## Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

---

## Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

---

## Question 61: Profit Margin After Discount

Calculate the new profit margin after applying discounts.

---

## Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

---

## Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.

---

## Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts.

---

# Part 11: Tax and Price Adjustment

The government introduces category-wise tax rates:

```python
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
```

## Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

---

## Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.

---

## Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

---

## Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

---

## Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount.

---

# Part 12: Array Modification

## Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

---

## Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

---

## Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

---

## Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using `np.delete()`.

---

## Question 74: Adding a New Store

A new Delhi store is opened with the following data:

```python
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
```

Add Delhi to both arrays using `np.vstack()`.

Also add `"Delhi"` to the stores array.

---

## Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

```python
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
```

Add the new category as a column using `np.column_stack()` or `np.hstack()`.

---

# Part 13: Sorting and Ranking

## Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.

---

## Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use `np.argsort()`.

---

## Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.

---

## Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

* Sales value
* Store name
* Category name

---

## Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

---

# Part 14: Statistical Analysis

## Question 81: Sales Statistics

Calculate the following for the complete sales array:

* Minimum
* Maximum
* Mean
* Median
* Standard deviation
* Variance
* 25th percentile
* 50th percentile
* 75th percentile

---

## Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

---

## Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.

---

## Question 84: Sales Above Company Average

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

---

## Question 85: Outlier Detection

Treat any sales value greater than:

```text
Mean + 1.5 × Standard Deviation
```

as a high-value outlier.

Identify all such sales values.

---

# Part 15: Reshaping and Transformation

## Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

* `flatten()`
* `ravel()`

Explain the difference between the two methods.

---

## Question 87: Reshape Sales Data

Reshape the `5 × 6` sales array into:

* `3 × 10`
* `10 × 3`
* `2 × 15`
* `15 × 2`

Verify that no data is lost.

---

## Question 88: Transpose Sales Data

Transpose the sales array so that:

* Rows represent product categories
* Columns represent stores

Display the new shape.

---

## Question 89: Combined Sales and Cost Array

Stack `sales_data` and `cost_data` vertically.

Display the resulting shape.

---

## Question 90: Store-Level Combined Data

Create a three-dimensional array where:

* First layer contains sales data
* Second layer contains cost data

Use `np.stack()`.

Display the shape of the new array.

---

# Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded.

```python
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
```

## Question 91: Missing Value Detection

Find:

* Total number of missing values
* Location of missing values
* Stores and categories containing missing values

---

## Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

---

## Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use `np.nanmean()`.

---

## Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

---

## Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

---

# Part 17: Conditional Business Decisions

## Question 96: Store Performance Labels

Classify each store based on total sales:

* `"Excellent"`: Total sales above ₹28,00,000
* `"Good"`: Total sales between ₹24,00,000 and ₹28,00,000
* `"Needs Improvement"`: Total sales below ₹24,00,000

Use `np.select()`.

---

## Question 97: Profitability Classification

Classify each store-category combination as:

* `"Highly Profitable"`: Profit above ₹2,00,000
* `"Profitable"`: Profit between ₹1,00,000 and ₹2,00,000
* `"Low Profit"`: Profit below ₹1,00,000
* `"Loss"`: Profit below zero

---

## Question 98: Expansion Recommendation

A store is eligible for expansion when:

* Total sales are above ₹25,00,000
* Total profit is above ₹7,00,000
* Overall profit margin is above 25%

Identify eligible stores.

---

## Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

* Average sales are below ₹3,00,000
* Profit margin is above 25%

Identify the categories that satisfy these conditions.

---

## Question 100: Cost Optimization Recommendation

Find store-category combinations where:

* Cost is greater than ₹2,50,000
* Profit margin is below 25%

These combinations should be reviewed for cost optimization.

---

# Part 18: Inventory Scenario

Use the following inventory arrays:

```python
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
```

## Question 101: Closing Stock

Calculate closing stock using:

```text
Closing Stock = Opening Stock - Units Sold
```

---

## Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.

---

## Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

---

## Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

---

## Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.

---

## Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

---

## Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

---

## Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

---

## Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

---

# Part 19: Advanced NumPy Questions

## Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using `np.cumsum()`.

---

## Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

---

## Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using `np.diff()`.

---

## Question 113: Unique Sales Values

Find all unique sales values in `sales_data`.

Also count the frequency of each value.

---

## Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

---

## Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using `np.all()`.

---

## Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

* Minimum: ₹75,000
* Maximum: ₹2,50,000

Use `np.clip()` to create a reporting profit array.

---

## Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

```text
Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)
```

---

## Question 118: Standardize Sales Data

Standardize sales using:

```text
Standardized Sales =
(Sales - Mean Sales) / Standard Deviation
```

---

## Question 119: Round Values

Convert profit margin values into:

* Two decimal places
* Nearest whole number
* Floor values
* Ceiling values

---

## Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

* `sales_data.npy`
* `cost_data.npy`
* `profit_data.npy`

Load them back and verify that the loaded arrays are equal to the original arrays.

---

# Part 20: Final Retail Analytics Project

Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

## Company Summary

1. Total company sales
2. Total company cost
3. Total company profit
4. Overall company profit margin
5. Average transaction value
6. Highest individual sales value
7. Lowest individual sales value

## Store Summary

For every store, display:

1. Total sales
2. Total cost
3. Total profit
4. Profit margin
5. Number of category targets achieved
6. Total units sold
7. Expansion eligibility

## Category Summary

For every category, display:

1. Total sales
2. Total cost
3. Total profit
4. Profit margin
5. Average sales
6. Number of stores achieving the target
7. Total units sold

## Management Recommendations

Based on the analysis, identify:

1. Best-performing store
2. Lowest-performing store
3. Most profitable category
4. Lowest-profit category
5. Store recommended for expansion
6. Category requiring additional marketing
7. Store-category combinations needing cost optimization
8. Store-category combinations requiring inventory reorder

---

# Expected Final Output Format

```text
SMARTMART RETAIL PERFORMANCE REPORT
===================================

COMPANY SUMMARY
---------------
Total Sales:
Total Cost:
Total Profit:
Overall Profit Margin:

BEST-PERFORMING STORE
---------------------
Store:
Sales:
Cost:
Profit:
Profit Margin:

MOST PROFITABLE CATEGORY
------------------------
Category:
Sales:
Cost:
Profit:
Profit Margin:

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:

COST OPTIMIZATION
-----------------
Store:
Category:
Cost:
Profit Margin:

INVENTORY REORDER
-----------------
Store:
Category:
Closing Stock:
Reorder Quantity:
```

---

# Assignment Rules

1. Use NumPy for all calculations.
2. Do not manually calculate or hard-code answers.
3. Avoid Python loops wherever a NumPy vectorized solution is possible.
4. Use axis-based operations correctly.
5. Display store and category names along with calculated values.
6. Round percentage values to two decimal places.
7. Use Boolean indexing for filtering questions.
8. Use broadcasting for target, discount, and tax calculations.
9. Do not modify the original arrays unless specifically instructed.
10. Add comments explaining the purpose of important calculations.

---

# Submission Requirements

Submit the assignment as a Jupyter Notebook containing:

1. Business scenario
2. Dataset creation
3. Question number and question description
4. NumPy solution below every question
5. Output for every solution
6. Final retail performance report
7. Minimum five business observations
8. Minimum three management recommendations


Part-1

In [13]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

In [14]:
#1
import numpy as np
print(sales_data.ndim)
print(sales_data.shape)
print(sales_data.size)
print(sales_data.dtype)
print(sales_data.nbytes)

2
(5, 6)
30
int64
240


In [15]:
#2
print(len(stores))
print(len(categories))
print(sales_data.size)

5
6
30


In [16]:
#3
print(sales_data.astype(np.float32).nbytes)
print(sales_data.astype(np.float64).nbytes)

120
240


Part 3: Indexing and Data Extraction

In [17]:
#4
print(sales_data[0])

[850000 420000 310000 275000 190000 225000]


In [18]:
#5
print(sales_data[0])

[850000 420000 310000 275000 190000 225000]


In [19]:
#6
print(sales_data[:, 0])

[ 850000  780000  920000 1050000  690000]


In [20]:
#7
print(sales_data[:, 0])

[ 850000  780000  920000 1050000  690000]


In [21]:
#8
sales = sales_data[1, 3]
cost = cost_data[1, 3]
profit = sales-cost

print("Sales:", sales)
print("Cost:", cost)
print("Profit:", profit)

Sales: 310000
Cost: 225000
Profit: 85000


In [22]:
#9
print(sales_data[2, 1:4])

[390000 340000 260000]


In [23]:
#10
print(sales_data[0:5:2, 0:5:2])

[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


Part 4 — Sales Aggregation

In [24]:
#11
print(np.sum(sales_data))

11675000


In [30]:
#12
store_sales = sales_data.sum(axis=1)
for store, value in zip(stores, store_sales):
    print(f"{store}: ₹{value:,}")

Bengaluru: ₹2,270,000
Hyderabad: ₹2,295,000
Chennai: ₹2,310,000
Mumbai: ₹2,820,000
Pune: ₹1,980,000


In [29]:
#13
category_sales = sales_data.sum(axis=0)
for category, value in zip(categories, category_sales):
    print(f"{category}: ₹{value:,}")

Electronics: ₹4,290,000
Groceries: ₹2,185,000
Clothing: ₹1,600,000
Furniture: ₹1,415,000
Beauty: ₹1,010,000
Sports: ₹1,175,000


In [28]:
#14
print(sales_data.mean(axis=1))

[378333.33333333 382500.         385000.         470000.
 330000.        ]


In [27]:
#15
print(sales_data.mean(axis=0))

[858000. 437000. 320000. 283000. 202000. 235000.]


In [31]:
#16
index = np.argmax(store_sales)
print("Index:", index)
print("Store:", stores[index])
print("Total Sales:", store_sales[index])

Index: 3
Store: Mumbai
Total Sales: 2820000


In [32]:
#17
index = np.argmin(store_sales)
print("Index:", index)
print("Store:", stores[index])
print("Total Sales:", store_sales[index])

Index: 4
Store: Pune
Total Sales: 1980000


In [33]:
#18
index = np.argmax(category_sales)
print("Index:", index)
print("Category:", categories[index])
print("Total Sales:", category_sales[index])

Index: 0
Category: Electronics
Total Sales: 4290000


In [34]:
#19
index = np.argmin(category_sales)
print("Index:", index)
print("Category:", categories[index])
print("Total Sales:", category_sales[index])

Index: 4
Category: Beauty
Total Sales: 1010000


Part 5: Cost Analysis

In [35]:
#20
print(np.sum(cost_data))

8600000


In [36]:
#21
store_costs = cost_data.sum(axis=1)
for store, value in zip(stores, store_costs):
    print(f"{store}: ₹{value:,}")

Bengaluru: ₹1,665,000
Hyderabad: ₹1,685,000
Chennai: ₹1,710,000
Mumbai: ₹2,065,000
Pune: ₹1,475,000


In [37]:
#22
category_costs = cost_data.sum(axis=0)
for category, value in zip(categories, category_costs):
    print(f"{category}: ₹{value:,}")

Electronics: ₹3,250,000
Groceries: ₹1,660,000
Clothing: ₹1,145,000
Furniture: ₹1,045,000
Beauty: ₹665,000
Sports: ₹835,000


In [38]:
#23
store_costs = np.sum(cost_data, axis=1)
max_store_index = np.argmax(store_costs)
most_expensive_store = stores[max_store_index]
max_cost = store_costs[max_store_index]
print(f"{most_expensive_store} with ₹{max_cost:,}")

Mumbai with ₹2,065,000


In [ ]:
#24
store_costs = np.sum(cost_data, axis=1)
min_store_index = np.argmin(store_costs)
least_expensive_store = stores[min_store_index]
min_cost = store_costs[min_store_index]
print(f"{least_expensive_store} with ₹{min_cost:,}")

Pune with ₹1,475,000


In [39]:
#25
category_costs = np.sum(cost_data, axis=0)
max_category_index = np.argmax(category_costs)
most_expensive_category = categories[max_category_index]
max_cost = category_costs[max_category_index]
print(f"{most_expensive_category} with ₹{max_cost:,}")

Electronics with ₹3,250,000


Part 6: Profit Analysis Using Two Arrays

In [40]:
#26
profit_data = sales_data - cost_data
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [41]:
#27
print(profit_data.sum(axis=1))

[605000 610000 600000 755000 505000]


In [42]:
#28
print(profit_data.sum(axis=0))

[1040000  525000  455000  370000  345000  340000]


In [43]:
#29
store_profits= profit_data.sum(axis=1)
index = np.argmax(store_profits)

print("Store:", stores[index])
print("Sales:", store_sales[index])
print("Cost:", store_costs[index])
print("Profit:", store_profits[index])

Store: Mumbai
Sales: 2820000
Cost: 2065000
Profit: 755000


In [44]:
#30
store_profits = profit_data.sum(axis=1)
index = np.argmin(store_profits)
print("Store:", stores[index])

Store: Pune


In [45]:
#31
category_profits = store_profits.sum(axis=0)
index = np.argmax(category_profits)
print("Category:", categories[index])

Category: Electronics


In [46]:
#32
category_profits = profit_data.sum(axis=0)
index = np.argmin(category_profits)
print("Category:", categories[index])

Category: Sports


In [48]:
#33
max_idx = np.argmax(profit_data)
store_idx, cat_idx = np.unravel_index(max_idx, profit_data.shape)
print("Profit Amount:", profit_data[store_idx, cat_idx])
print("Store Name:", stores[store_idx])
print("Product Category:", categories[cat_idx])

Profit Amount: 260000
Store Name: Mumbai
Product Category: Electronics


In [52]:
#34
min_idx = np.argmin(profit_data)
store_idx, cat_idx = np.unravel_index(min_idx, profit_data.shape)
print("Profit Amount:", profit_data[store_idx, cat_idx])

Profit Amount: 55000


Part 7: Profit Margin Analysis

In [54]:
#35
profit_margin = np.round((profit_data / sales_data) * 100, 2)
print(profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [63]:
#36
store_profit_margin = np.round((store_profits / store_sales) * 100, 2)
for store, margin in zip(stores, store_profit_margin):
    print(f"{store}: {margin}%")

Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%


In [80]:
#37
category_profit_margin = np.round((category_profits / category_sales) * 100, 2)
for category, margin in zip(categories, category_profit_margin):
    print(f"{category}: {margin}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%


In [81]:
#38
best_margin_store_idx = np.argmax(store_profit_margin)
print("Store:", stores[best_margin_store_idx])
print("Profit Margin:", store_profit_margin[best_margin_store_idx], "%")

Store: Mumbai
Profit Margin: 26.77 %


In [83]:
#39
best_margin_category_idx = np.argmax(category_profit_margin)
print("Category:", categories[best_margin_category_idx])
print("Profit Margin:", category_profit_margin[best_margin_category_idx], "%")

Category: Beauty
Profit Margin: 34.16 %


In [108]:
#40
x= profit_margin < 22.0
store_idx_arr, cat_idx_arr = np.where(x)
for s_idx, c_idx in zip(store_idx_arr, cat_idx_arr):
    print(
        f"Store: {stores[s_idx]}, "
        f"Category: {categories[c_idx]}, "
        f"Sales: {sales_data[s_idx, c_idx]}, "
        f"Cost: {cost_data[s_idx, c_idx]}, "
        f"Profit: {profit_data[s_idx, c_idx]}, "
        f"Profit margin: {profit_margin[s_idx, c_idx]}%"
    )

Store: Bengaluru, Category: Electronics, Sales: 850000, Cost: 640000, Profit: 210000, Profit margin: 0.24705882352941178%
Store: Bengaluru, Category: Groceries, Sales: 420000, Cost: 315000, Profit: 105000, Profit margin: 0.25%
Store: Bengaluru, Category: Clothing, Sales: 310000, Cost: 220000, Profit: 90000, Profit margin: 0.2903225806451613%
Store: Bengaluru, Category: Furniture, Sales: 275000, Cost: 205000, Profit: 70000, Profit margin: 0.2545454545454545%
Store: Bengaluru, Category: Beauty, Sales: 190000, Cost: 125000, Profit: 65000, Profit margin: 0.34210526315789475%
Store: Bengaluru, Category: Sports, Sales: 225000, Cost: 160000, Profit: 65000, Profit margin: 0.28888888888888886%
Store: Hyderabad, Category: Electronics, Sales: 780000, Cost: 590000, Profit: 190000, Profit margin: 0.24358974358974358%
Store: Hyderabad, Category: Groceries, Sales: 460000, Cost: 350000, Profit: 110000, Profit margin: 0.2391304347826087%
Store: Hyderabad, Category: Clothing, Sales: 295000, Cost: 210000