<a href="https://colab.research.google.com/github/mamudurujagadeesh7-cloud/Edukron-DS/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Retail Analytics Assignment

## Business Scenario

You are working as a Data Analyst for **SmartMart Retail Stores**. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

1. `sales_data` — monthly sales revenue generated by each store for different product categories.
2. `cost_data` — total cost incurred by each store for the same product categories.

---

# Part 1: Dataset Creation

```python
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)
```

---

# Part 2: Basic Array Understanding

## Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

* Number of dimensions in `sales_data`
* Shape of `sales_data`
* Total number of values
* Data type of the array
* Memory occupied by the array

---

## Question 2: Store and Category Count

Calculate the following:

* Total number of stores
* Total number of product categories
* Total number of store-category combinations

---

## Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert `sales_data` into:

* `float32`
* `float64`

Compare the memory used by both arrays.

---

# Part 3: Indexing and Data Extraction

## Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

---

## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

---

## Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from `sales_data`.

---

## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

---

## Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

* Furniture sales
* Furniture cost
* Furniture profit

---

## Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

* Groceries
* Clothing
* Furniture

Use array slicing.

---

## Question 10: Selected Store Analysis

Extract sales data for:

* Bengaluru
* Chennai
* Pune

Include only:

* Electronics
* Clothing
* Beauty

Use advanced indexing.

---

# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

---

## Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

```text
Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales
```

---

## Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

---

## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

---

## Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

---

## Question 16: Highest-Selling Store

Identify:

* Index of the store with the highest total sales
* Name of the store
* Total sales generated by that store

Use `np.argmax()`.

---

## Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use `np.argmin()`.

---

## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

---

## Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

---

# Part 5: Cost Analysis

## Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

---

## Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

---

## Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

---

## Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

---

## Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

---

## Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

---

# Part 6: Profit Analysis Using Two Arrays

## Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:

```python
profit_data = sales_data - cost_data
```

Display the complete profit matrix.

---

## Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

---

## Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

---

## Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

Display:

* Store name
* Total sales
* Total cost
* Total profit

---

## Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

---

## Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

---

## Question 32: Least Profitable Category

Find the category with the lowest total profit.

---

## Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

* Profit amount
* Store name
* Product category

Use `np.unravel_index()`.

---

## Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

---

# Part 7: Profit Margin Analysis

## Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:

```python
profit_margin = (profit_data / sales_data) * 100
```

Round the result to two decimal places.

---

## Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

```text
Store Profit Margin =
Total Store Profit / Total Store Sales × 100
```

---

## Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

---

## Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

---

## Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

---

## Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

* Store
* Category
* Sales
* Cost
* Profit
* Profit margin

Use Boolean indexing.

---

# Part 8: Boolean Filtering

## Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

---

## Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

---

## Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

---

## Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use `np.logical_and()`.

---

## Question 45: Premium Performance

A store-category combination is considered premium when:

* Sales are greater than ₹5,00,000
* Profit is greater than ₹1,50,000

Find all premium-performing combinations.

---

## Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

* Sales are below ₹2,50,000
* Profit margin is below 25%

Find all such combinations.

---

## Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

* `"High"` when sales are at least ₹5,00,000
* `"Medium"` when sales are between ₹2,50,000 and ₹4,99,999
* `"Low"` when sales are below ₹2,50,000

Use `np.where()` or `np.select()`.

---

# Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

```python
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
```

## Question 48: Target Comparison

Compare every store’s category sales against `sales_targets`.

Use NumPy broadcasting.

---

## Question 49: Target Achievement Matrix

Create a Boolean array where:

* `True` means the store achieved the category target
* `False` means the store failed to achieve the target

---

## Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

---

## Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

---

## Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

---

## Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use:

```text
Variance = Actual Sales - Target Sales
```

---

## Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

```text
Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100
```

---

## Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

---

## Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use `np.all()`.

---

## Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use `np.any()`.

---

# Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:

```python
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
```

## Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.

---

## Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

---

## Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

---

## Question 61: Profit Margin After Discount

Calculate the new profit margin after applying discounts.

---

## Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

---

## Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.

---

## Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts.

---

# Part 11: Tax and Price Adjustment

The government introduces category-wise tax rates:

```python
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
```

## Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

---

## Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.

---

## Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

---

## Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

---

## Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount.

---

# Part 12: Array Modification

## Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

---

## Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

---

## Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

---

## Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using `np.delete()`.

---

## Question 74: Adding a New Store

A new Delhi store is opened with the following data:

```python
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
```

Add Delhi to both arrays using `np.vstack()`.

Also add `"Delhi"` to the stores array.

---

## Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

```python
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
```

Add the new category as a column using `np.column_stack()` or `np.hstack()`.

---

# Part 13: Sorting and Ranking

## Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.

---

## Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use `np.argsort()`.

---

## Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.

---

## Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

* Sales value
* Store name
* Category name

---

## Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

---

# Part 14: Statistical Analysis

## Question 81: Sales Statistics

Calculate the following for the complete sales array:

* Minimum
* Maximum
* Mean
* Median
* Standard deviation
* Variance
* 25th percentile
* 50th percentile
* 75th percentile

---

## Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

---

## Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.

---

## Question 84: Sales Above Company Average

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

---

## Question 85: Outlier Detection

Treat any sales value greater than:

```text
Mean + 1.5 × Standard Deviation
```

as a high-value outlier.

Identify all such sales values.

---

# Part 15: Reshaping and Transformation

## Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

* `flatten()`
* `ravel()`

Explain the difference between the two methods.

---

## Question 87: Reshape Sales Data

Reshape the `5 × 6` sales array into:

* `3 × 10`
* `10 × 3`
* `2 × 15`
* `15 × 2`

Verify that no data is lost.

---

## Question 88: Transpose Sales Data

Transpose the sales array so that:

* Rows represent product categories
* Columns represent stores

Display the new shape.

---

## Question 89: Combined Sales and Cost Array

Stack `sales_data` and `cost_data` vertically.

Display the resulting shape.

---

## Question 90: Store-Level Combined Data

Create a three-dimensional array where:

* First layer contains sales data
* Second layer contains cost data

Use `np.stack()`.

Display the shape of the new array.

---

# Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded.

```python
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
```

## Question 91: Missing Value Detection

Find:

* Total number of missing values
* Location of missing values
* Stores and categories containing missing values

---

## Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

---

## Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use `np.nanmean()`.

---

## Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

---

## Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

---

# Part 17: Conditional Business Decisions

## Question 96: Store Performance Labels

Classify each store based on total sales:

* `"Excellent"`: Total sales above ₹28,00,000
* `"Good"`: Total sales between ₹24,00,000 and ₹28,00,000
* `"Needs Improvement"`: Total sales below ₹24,00,000

Use `np.select()`.

---

## Question 97: Profitability Classification

Classify each store-category combination as:

* `"Highly Profitable"`: Profit above ₹2,00,000
* `"Profitable"`: Profit between ₹1,00,000 and ₹2,00,000
* `"Low Profit"`: Profit below ₹1,00,000
* `"Loss"`: Profit below zero

---

## Question 98: Expansion Recommendation

A store is eligible for expansion when:

* Total sales are above ₹25,00,000
* Total profit is above ₹7,00,000
* Overall profit margin is above 25%

Identify eligible stores.

---

## Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

* Average sales are below ₹3,00,000
* Profit margin is above 25%

Identify the categories that satisfy these conditions.

---

## Question 100: Cost Optimization Recommendation

Find store-category combinations where:

* Cost is greater than ₹2,50,000
* Profit margin is below 25%

These combinations should be reviewed for cost optimization.

---

# Part 18: Inventory Scenario

Use the following inventory arrays:

```python
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
```

## Question 101: Closing Stock

Calculate closing stock using:

```text
Closing Stock = Opening Stock - Units Sold
```

---

## Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.

---

## Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

---

## Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

---

## Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.

---

## Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

---

## Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

---

## Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

---

## Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

---

# Part 19: Advanced NumPy Questions

## Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using `np.cumsum()`.

---

## Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

---

## Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using `np.diff()`.

---

## Question 113: Unique Sales Values

Find all unique sales values in `sales_data`.

Also count the frequency of each value.

---

## Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

---

## Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using `np.all()`.

---

## Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

* Minimum: ₹75,000
* Maximum: ₹2,50,000

Use `np.clip()` to create a reporting profit array.

---

## Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

```text
Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)
```

---

## Question 118: Standardize Sales Data

Standardize sales using:

```text
Standardized Sales =
(Sales - Mean Sales) / Standard Deviation
```

---

## Question 119: Round Values

Convert profit margin values into:

* Two decimal places
* Nearest whole number
* Floor values
* Ceiling values

---

## Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

* `sales_data.npy`
* `cost_data.npy`
* `profit_data.npy`

Load them back and verify that the loaded arrays are equal to the original arrays.

---

# Part 20: Final Retail Analytics Project

Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

## Company Summary

1. Total company sales
2. Total company cost
3. Total company profit
4. Overall company profit margin
5. Average transaction value
6. Highest individual sales value
7. Lowest individual sales value

## Store Summary

For every store, display:

1. Total sales
2. Total cost
3. Total profit
4. Profit margin
5. Number of category targets achieved
6. Total units sold
7. Expansion eligibility

## Category Summary

For every category, display:

1. Total sales
2. Total cost
3. Total profit
4. Profit margin
5. Average sales
6. Number of stores achieving the target
7. Total units sold

## Management Recommendations

Based on the analysis, identify:

1. Best-performing store
2. Lowest-performing store
3. Most profitable category
4. Lowest-profit category
5. Store recommended for expansion
6. Category requiring additional marketing
7. Store-category combinations needing cost optimization
8. Store-category combinations requiring inventory reorder

---

# Expected Final Output Format

```text
SMARTMART RETAIL PERFORMANCE REPORT
===================================

COMPANY SUMMARY
---------------
Total Sales:
Total Cost:
Total Profit:
Overall Profit Margin:

BEST-PERFORMING STORE
---------------------
Store:
Sales:
Cost:
Profit:
Profit Margin:

MOST PROFITABLE CATEGORY
------------------------
Category:
Sales:
Cost:
Profit:
Profit Margin:

EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:

COST OPTIMIZATION
-----------------
Store:
Category:
Cost:
Profit Margin:

INVENTORY REORDER
-----------------
Store:
Category:
Closing Stock:
Reorder Quantity:
```

---

# Assignment Rules

1. Use NumPy for all calculations.
2. Do not manually calculate or hard-code answers.
3. Avoid Python loops wherever a NumPy vectorized solution is possible.
4. Use axis-based operations correctly.
5. Display store and category names along with calculated values.
6. Round percentage values to two decimal places.
7. Use Boolean indexing for filtering questions.
8. Use broadcasting for target, discount, and tax calculations.
9. Do not modify the original arrays unless specifically instructed.
10. Add comments explaining the purpose of important calculations.

---

# Submission Requirements

Submit the assignment as a Jupyter Notebook containing:

1. Business scenario
2. Dataset creation
3. Question number and question description
4. NumPy solution below every question
5. Output for every solution
6. Final retail performance report
7. Minimum five business observations
8. Minimum three management recommendations


# Part-1

In [108]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


# Part 2: Basic Array Understanding

In [109]:
#1
import numpy as np
print(sales_data.ndim)
print(sales_data.shape)
print(sales_data.size)
print(sales_data.dtype)
print(sales_data.nbytes)

2
(5, 6)
30
int64
240


In [110]:
#2
print(len(stores))
print(len(categories))
print(sales_data.size)

5
6
30


In [111]:
#3
print(sales_data.astype(np.float32).nbytes)
print(sales_data.astype(np.float64).nbytes)

120
240


# Part 3: Indexing and Data Extraction

In [112]:
#4
print(sales_data[0])

[850000 420000 310000 275000 190000 225000]


In [113]:
#5
print(sales_data[0])

[850000 420000 310000 275000 190000 225000]


In [114]:
#6
print(sales_data[:, 0])

[ 850000  780000  920000 1050000  690000]


In [115]:
#7
print(sales_data[:, 0])

[ 850000  780000  920000 1050000  690000]


In [116]:
#8
sales = sales_data[1, 3]
cost = cost_data[1, 3]
profit = sales-cost

print("Sales:", sales)
print("Cost:", cost)
print("Profit:", profit)

Sales: 310000
Cost: 225000
Profit: 85000


In [117]:
#9
print(sales_data[2, 1:4])

[390000 340000 260000]


In [118]:
#10
print(sales_data[0:5:2, 0:5:2])

[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


# Part 4 — Sales Aggregation

In [119]:
#11
print(np.sum(sales_data))

11675000


In [120]:
#12
store_sales = sales_data.sum(axis=1)
for store, value in zip(stores, store_sales):
    print(f"{store}: ₹{value:,}")

Bengaluru: ₹2,270,000
Hyderabad: ₹2,295,000
Chennai: ₹2,310,000
Mumbai: ₹2,820,000
Pune: ₹1,980,000


In [121]:
#13
category_sales = sales_data.sum(axis=0)
for category, value in zip(categories, category_sales):
    print(f"{category}: ₹{value:,}")

Electronics: ₹4,290,000
Groceries: ₹2,185,000
Clothing: ₹1,600,000
Furniture: ₹1,415,000
Beauty: ₹1,010,000
Sports: ₹1,175,000


In [122]:
#14
print(sales_data.mean(axis=1))

[378333.33333333 382500.         385000.         470000.
 330000.        ]


In [123]:
#15
print(sales_data.mean(axis=0))

[858000. 437000. 320000. 283000. 202000. 235000.]


In [124]:
#16
index = np.argmax(store_sales)
print("Index:", index)
print("Store:", stores[index])
print("Total Sales:", store_sales[index])

Index: 3
Store: Mumbai
Total Sales: 2820000


In [125]:
#17
index = np.argmin(store_sales)
print("Index:", index)
print("Store:", stores[index])
print("Total Sales:", store_sales[index])

Index: 4
Store: Pune
Total Sales: 1980000


In [126]:
#18
index = np.argmax(category_sales)
print("Index:", index)
print("Category:", categories[index])
print("Total Sales:", category_sales[index])

Index: 0
Category: Electronics
Total Sales: 4290000


In [127]:
#19
index = np.argmin(category_sales)
print("Index:", index)
print("Category:", categories[index])
print("Total Sales:", category_sales[index])

Index: 4
Category: Beauty
Total Sales: 1010000


# Part 5: Cost Analysis

In [128]:
#20
print(np.sum(cost_data))

8600000


In [129]:
#21
store_costs = cost_data.sum(axis=1)
for store, value in zip(stores, store_costs):
    print(f"{store}: ₹{value:,}")

Bengaluru: ₹1,665,000
Hyderabad: ₹1,685,000
Chennai: ₹1,710,000
Mumbai: ₹2,065,000
Pune: ₹1,475,000


In [130]:
#22
category_costs = cost_data.sum(axis=0)
for category, value in zip(categories, category_costs):
    print(f"{category}: ₹{value:,}")

Electronics: ₹3,250,000
Groceries: ₹1,660,000
Clothing: ₹1,145,000
Furniture: ₹1,045,000
Beauty: ₹665,000
Sports: ₹835,000


In [131]:
#23
store_costs = np.sum(cost_data, axis=1)
max_store_index = np.argmax(store_costs)
most_expensive_store = stores[max_store_index]
max_cost = store_costs[max_store_index]
print(f"{most_expensive_store} with ₹{max_cost:,}")

Mumbai with ₹2,065,000


In [132]:
#24
store_costs = np.sum(cost_data, axis=1)
min_store_index = np.argmin(store_costs)
least_expensive_store = stores[min_store_index]
min_cost = store_costs[min_store_index]
print(f"{least_expensive_store} with ₹{min_cost:,}")

Pune with ₹1,475,000


In [133]:
#25
category_costs = np.sum(cost_data, axis=0)
max_category_index = np.argmax(category_costs)
most_expensive_category = categories[max_category_index]
max_cost = category_costs[max_category_index]
print(f"{most_expensive_category} with ₹{max_cost:,}")

Electronics with ₹3,250,000


# Part 6: Profit Analysis Using Two Arrays

In [134]:
#26
profit_data = sales_data - cost_data
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [135]:
#27
print(profit_data.sum(axis=1))

[605000 610000 600000 755000 505000]


In [136]:
#28
print(profit_data.sum(axis=0))

[1040000  525000  455000  370000  345000  340000]


In [137]:
#29
store_profits= profit_data.sum(axis=1)
index = np.argmax(store_profits)

print("Store:", stores[index])
print("Sales:", store_sales[index])
print("Cost:", store_costs[index])
print("Profit:", store_profits[index])

Store: Mumbai
Sales: 2820000
Cost: 2065000
Profit: 755000


In [138]:
#30
store_profits = profit_data.sum(axis=1)
index = np.argmin(store_profits)
print("Store:", stores[index])

Store: Pune


In [139]:
#31
category_profits = profit_data.sum(axis=0)
index = np.argmax(category_profits)
print("Category:", categories[index])

Category: Electronics


In [140]:
#32
category_profits = profit_data.sum(axis=0)
index = np.argmin(category_profits)
print("Category:", categories[index])

Category: Sports


In [141]:
#33
max_idx = np.argmax(profit_data)
store_idx, cat_idx = np.unravel_index(max_idx, profit_data.shape)
print("Profit Amount:", profit_data[store_idx, cat_idx])
print("Store Name:", stores[store_idx])
print("Product Category:", categories[cat_idx])

Profit Amount: 260000
Store Name: Mumbai
Product Category: Electronics


In [142]:
#34
min_idx = np.argmin(profit_data)
store_idx, cat_idx = np.unravel_index(min_idx, profit_data.shape)
print("Profit Amount:", profit_data[store_idx, cat_idx])

Profit Amount: 55000


# Part 7: Profit Margin Analysis

In [143]:
#35
profit_margin = np.round((profit_data / sales_data) * 100, 2)
print(profit_margin)

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [144]:
#36
store_profit_margin = np.round((store_profits / store_sales) * 100, 2)
for store, margin in zip(stores, store_profit_margin):
    print(f"{store}: {margin}%")

Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%


In [145]:
#37
category_profit_margin = np.round((category_profits / category_sales) * 100, 2)
for category, margin in zip(categories, category_profit_margin):
    print(f"{category}: {margin}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%


In [146]:
#38
best_margin_store_idx = np.argmax(store_profit_margin)
print("Store:", stores[best_margin_store_idx])
print("Profit Margin:", store_profit_margin[best_margin_store_idx], "%")

Store: Mumbai
Profit Margin: 26.77 %


In [147]:
#39
best_margin_category_idx = np.argmax(category_profit_margin)
print("Category:", categories[best_margin_category_idx])
print("Profit Margin:", category_profit_margin[best_margin_category_idx], "%")

Category: Beauty
Profit Margin: 34.16 %


In [148]:
#40
x= profit_margin < 22.0
store_idx_arr, cat_idx_arr = np.where(x)
for s_idx, c_idx in zip(store_idx_arr, cat_idx_arr):
    print(
        f"Store: {stores[s_idx]}, "
        f"Category: {categories[c_idx]}, "
        f"Sales: {sales_data[s_idx, c_idx]}, "
        f"Cost: {cost_data[s_idx, c_idx]}, "
        f"Profit: {profit_data[s_idx, c_idx]}, "
        f"Profit margin: {profit_margin[s_idx, c_idx]}%"
    )

# Part 8: Boolean Filtering

In [149]:
#41
print(sales_data[sales_data > 500000])

[ 850000  780000  920000 1050000  510000  690000]


In [150]:
#42
print(sales_data[sales_data < 200000])

[190000 185000 175000]


In [151]:
#43
rows, cols = np.where(profit_data > 150000)

for r, c in zip(rows, cols):
    print(stores[r], categories[c], profit_data[r, c])

Bengaluru Electronics 210000
Hyderabad Electronics 190000
Chennai Electronics 220000
Mumbai Electronics 260000
Pune Electronics 160000


In [152]:
#44
x= np.logical_and(
    sales_data >= 250000,
    sales_data <= 500000
)

print(sales_data[x])

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [153]:
#45
x = np.logical_and(
    sales_data > 500000,
    profit_data > 150000
)

rows, cols = np.where(x)

for r, c in zip(rows, cols):
    print(
        stores[r],
        categories[c],
        sales_data[r, c],
        profit_data[r, c]
    )

Bengaluru Electronics 850000 210000
Hyderabad Electronics 780000 190000
Chennai Electronics 920000 220000
Mumbai Electronics 1050000 260000
Pune Electronics 690000 160000


In [154]:
#46
x = np.logical_and(
    sales_data < 250000,
    profit_margin < 25
)

rows, cols = np.where(x)

for r, c in zip(rows, cols):
    print(
        stores[r],
        categories[c],
        sales_data[r, c],
        profit_data[r, c]
    )

Pune Furniture 225000 55000


In [155]:
#47
sales_condition = np.where(sales_data < 250000,"Low",np.where(sales_data >=500000
,"High","Medium"))
print(sales_condition)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


# Part 9: Target-Based Analysis

In [156]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [157]:
#48
target_variance = sales_data - sales_targets
print(target_variance)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [158]:
#49
target_achieved = sales_data >= sales_targets
print(target_achieved)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [159]:
#50
target_count = np.sum(target_achieved, axis=1)
for store, count in zip(stores, target_count):
    print(store, ":", count)

Bengaluru : 1
Hyderabad : 4
Chennai : 2
Mumbai : 6
Pune : 0


In [160]:
#51
idx = np.argmax(target_count)

print("Store:", stores[idx])
print("Targets achieved:", target_count[idx])

Store: Mumbai
Targets achieved: 6


In [161]:
#52
category_target_count = target_achieved.sum(axis=0)
for category, count in zip(categories, category_target_count):
    print(category, ":", count)

Electronics : 3
Groceries : 2
Clothing : 2
Furniture : 2
Beauty : 2
Sports : 2


In [162]:
#53
print(sales_data - sales_targets)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [163]:
#54
percentage_variance = ((sales_data - sales_targets) / sales_targets) * 100
print(np.round(percentage_variance, 2))

[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


In [164]:
#55
a = sales_data[:, 0] < sales_targets[0]
print(stores[a])

['Hyderabad' 'Pune']


In [165]:
#56
all_targets = np.all(target_achieved, axis=1)
print(all_targets)
print("Stores:", stores[all_targets])

[False False False  True False]
Stores: ['Mumbai']


In [166]:
#57
some_targets = np.any(target_achieved, axis=1)
print(stores[some_targets])

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


# Part 10: Discount Scenario

In [167]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [168]:
#58
discount_amount = sales_data * discount_rates
print(discount_amount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [169]:
#59
sales_after_discount = sales_data - discount_amount
print(sales_after_discount)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [170]:
#60
profit_after_discount = sales_after_discount - cost_data
print(profit_after_discount)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [171]:
#61
margin_after_discount = (profit_after_discount / sales_after_discount) * 100
print(np.round(margin_after_discount, 2))

[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


In [172]:
#62
loss_mask = profit_after_discount < 0
rows, cols = np.where(loss_mask)
if len(rows) == 0:
    print("No loss-making transactions.")
else:
    for r, c in zip(rows, cols):
        print(stores[r], categories[c])

No loss-making transactions.


In [173]:
#63
total_discount_loss = np.sum(discount_amount)
print("Total revenue lost:", total_discount_loss)

Total revenue lost: 1146350.0


In [174]:
#64
store_discount_loss = np.sum(discount_amount, axis=1)
idx = np.argmax(store_discount_loss)
print("Store:", stores[idx])
print("Revenue lost:", store_discount_loss[idx])

Store: Mumbai
Revenue lost: 277150.0


# Part 11 — Tax

In [175]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [176]:
#65
tax_collection = sales_data * tax_rates
print(tax_collection)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [177]:
#66
sales_including_tax = sales_data + tax_collection
print(sales_including_tax)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [178]:
#67
store_tax = np.sum(tax_collection, axis=1)
for store, tax in zip(stores, store_tax):
    print(store, ":", tax)

Bengaluru : 321900.0
Hyderabad : 321200.0
Chennai : 331800.0
Mumbai : 401400.0
Pune : 274650.0


In [179]:
#68
category_tax = np.sum(tax_collection, axis=0)
for category, tax in zip(categories, category_tax):
    print(category, ":", tax)

Electronics : 772200.0
Groceries : 109250.0
Clothing : 192000.0
Furniture : 254700.0
Beauty : 181800.0
Sports : 141000.0


In [180]:
#69
idx = np.argmax(store_tax)
print("Store:", stores[idx])
print("Tax:", store_tax[idx])

Store: Mumbai
Tax: 401400.0


# Part 12: Array Modification

In [181]:
#70
updated_sales = sales_data.copy()
updated_sales[4, 0] = 740000
print("Original Pune Electronics:", sales_data[4, 0])
print("Updated Pune Electronics:", updated_sales[4, 0])

Original Pune Electronics: 690000
Updated Pune Electronics: 740000


In [182]:
#71
updated_cost = cost_data.copy()
updated_cost[:, 4] =updated_cost[:, 4]-updated_cost[:, 4] * 0.08
print(updated_cost)

[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


In [183]:
#72
furniture_updated_cost = cost_data.copy()
furniture_updated_cost[:, 3] = furniture_updated_cost[:, 3]+furniture_updated_cost[:, 3]*0.12
print(furniture_updated_cost)

[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


In [184]:
#73
sales_without_pune = np.delete(sales_data, 4, axis=0)
cost_without_pune = np.delete(cost_data, 4, axis=0)

print("Sales shape:", sales_without_pune.shape)
print("Cost shape:", cost_without_pune.shape)

Sales shape: (4, 6)
Cost shape: (4, 6)


In [185]:
#74
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

sales_with_delhi = np.vstack((sales_data, delhi_sales))
cost_with_delhi = np.vstack((cost_data, delhi_cost))
stores_with_delhi = np.append(stores, "Delhi")

print("Stores:", stores_with_delhi)
print("Sales shape:", sales_with_delhi.shape)
print("Cost shape:", cost_with_delhi.shape)

Stores: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']
Sales shape: (6, 6)
Cost shape: (6, 6)


In [186]:
#75
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

sales_with_home = np.column_stack(
    (sales_data, home_appliance_sales)
)

cost_with_home = np.column_stack(
    (cost_data, home_appliance_cost)
)

categories_with_home = np.append(
    categories, "Home Appliances"
)

print("New shape:", sales_with_home.shape)
print("Categories:", categories_with_home)

New shape: (5, 7)
Categories: ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']


# Part 13: Sorting and Ranking

In [187]:
#76
order = np.argsort(store_sales)
for i in order:
    print(f"{stores[i]}: ₹{store_sales[i]:,.0f}")

Pune: ₹1,980,000
Bengaluru: ₹2,270,000
Hyderabad: ₹2,295,000
Chennai: ₹2,310,000
Mumbai: ₹2,820,000


In [188]:
#77
order = np.argsort(store_profits)[::-1]
for rank, i in enumerate(order, start=1):
    print(f"{rank}. {stores[i]} - ₹{store_profits[i]:,.0f}")

1. Mumbai - ₹755,000
2. Hyderabad - ₹610,000
3. Bengaluru - ₹605,000
4. Chennai - ₹600,000
5. Pune - ₹505,000


In [189]:
#78
order = np.argsort(category_sales)[::-1]
for i in order:
    print(f"{categories[i]}: ₹{category_sales[i]:,.0f}")

Electronics: ₹4,290,000
Groceries: ₹2,185,000
Clothing: ₹1,600,000
Furniture: ₹1,415,000
Sports: ₹1,175,000
Beauty: ₹1,010,000


In [190]:
#79
flat_order = np.argsort(sales_data, axis=None)[::-1][:3]
rows, cols = np.unravel_index(flat_order, sales_data.shape)

for r, c in zip(rows, cols):
    print(
        f"{stores[r]} - {categories[c]}: "
        f"₹{sales_data[r,c]:,.0f}"
    )

Mumbai - Electronics: ₹1,050,000
Chennai - Electronics: ₹920,000
Bengaluru - Electronics: ₹850,000


In [191]:
#80
flat_order = np.argsort(profit_data, axis=None)[:3]
rows, cols = np.unravel_index(flat_order, profit_data.shape)

for r, c in zip(rows, cols):
    print(
        f"{stores[r]} - {categories[c]}: "
        f"₹{profit_data[r,c]:,.0f}")

Pune - Furniture: ₹55,000
Pune - Sports: ₹60,000
Chennai - Sports: ₹60,000


# Part 14 — Statistical Analysis

In [192]:
#81
print("Minimum:", sales_data.min())
print("Maximum:", sales_data.max())
print("Mean:", sales_data.mean())
print("Median:", np.median(sales_data))
print("Standard deviation:", sales_data.std())
print("Variance:", sales_data.var())
print("25th percentile:", np.percentile(sales_data, 25))
print("50th percentile:", np.percentile(sales_data, 50))
print("75th percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard deviation: 230322.53954448793
Variance: 53048472222.222206
25th percentile: 228750.0
50th percentile: 302500.0
75th percentile: 416250.0


In [193]:
#82
store_std = sales_data.std(axis=1)
for store, value in zip(stores, store_std):
    print(f"{store}: ₹{value:,.2f}")
idx = np.argmax(store_std)
print("Highest variation:", stores[idx])

Bengaluru: ₹223,059.53
Hyderabad: ₹194,502.57
Chennai: ₹249,265.59
Mumbai: ₹271,860.87
Pune: ₹177,200.45
Highest variation: Mumbai


In [194]:
#83
category_std = sales_data.std(axis=0)
for category, value in zip(categories, category_std):
    print(f"{category}: ₹{value:,.2f}")
idx = np.argmax(category_std)
print("Highest variation:", categories[idx])

Electronics: ₹122,539.79
Groceries: ₹43,312.82
Clothing: ₹33,911.65
Furniture: ₹41,303.75
Beauty: ₹26,570.66
Sports: ₹29,832.87
Highest variation: Electronics


In [195]:
#84
company_average = sales_data.mean()
above_average = sales_data > company_average
print("Company average:", company_average)
print("Number above average:", np.sum(above_average))

Company average: 389166.6666666667
Number above average: 10


In [196]:
#85
mean_sales = sales_data.mean()
std_sales = sales_data.std()
X = mean_sales + 1.5 * std_sales
outliers = sales_data[sales_data > X]
print("Outlier threshold:", X)
print("Outliers:", outliers)

Outlier threshold: 734650.4759833985
Outliers: [ 850000  780000  920000 1050000]


#Part 15 — Reshaping and Transformation

In [197]:
#86
flat_sales = sales_data.flatten()
ravel_sales = sales_data.ravel()
print("Flatten:")
print(flat_sales)
print("Ravel:")
print(ravel_sales)
print("Same values:", np.array_equal(flat_sales, ravel_sales))

Flatten:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
Ravel:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
Same values: True


In [198]:
#87
sales1 = sales_data.reshape(3,10)
sales2 = sales_data.reshape(10,3)
sales3 = sales_data.reshape(2,15)
sales4 = sales_data.reshape(15,2)
sale=[sales1,sales2,sales3,sales4]
for i in sale:
    print(i.size==sales_data.size)

True
True
True
True


In [199]:
#88
transposed_sales = sales_data.transpose()

print(transposed_sales)
print("New shape:", transposed_sales.shape)

[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
New shape: (6, 5)


In [200]:
#89
combined = np.vstack((sales_data, cost_data))
print("Shape:", combined.shape)

Shape: (10, 6)


In [201]:
#90
sales_cost_3d = np.stack((sales_data, cost_data))
print("Shape:", sales_cost_3d.shape)
print(sales_cost_3d)

Shape: (2, 5, 6)
[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]


# Part 16 — Missing Data

In [202]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

In [203]:
#91
missing_mask = np.isnan(sales_with_missing)
print("Total missing:", missing_mask.sum())
rows, cols = np.where(missing_mask)
for r, c in zip(rows, cols):
    print(
        f"{stores[r]} - {categories[c]}"
    )

Total missing: 4
Bengaluru - Clothing
Hyderabad - Furniture
Mumbai - Groceries
Pune - Beauty


In [204]:
#92
sales_zero = np.nan_to_num(sales_with_missing,nan=0)
print(sales_zero)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [205]:
#93
avg_value = round(np.nanmean(sales_with_missing),2)
filled_avg_value = np.nan_to_num(sales_with_missing,nan=avg_value)
print(filled_avg_value)

[[ 850000.    420000.    398846.15  275000.    190000.    225000.  ]
 [ 780000.    460000.    295000.    398846.15  210000.    240000.  ]
 [ 920000.    390000.    340000.    260000.    185000.    215000.  ]
 [1050000.    398846.15  375000.    345000.    250000.    290000.  ]
 [ 690000.    405000.    280000.    225000.    398846.15  205000.  ]]


In [206]:
#94
category_avg_missing = np.nanmean(
    sales_with_missing,
    axis=0
)
sales_category_filled = np.where(
    np.isnan(sales_with_missing),
    category_avg_missing,
    sales_with_missing
)
print("Category averages:")
print(category_avg_missing)

print("\nFilled data:")
print(sales_category_filled)

Category averages:
[858000. 418750. 322500. 276250. 208750. 235000.]

Filled data:
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


In [207]:
#95
before = np.nansum(sales_with_missing)
after = sales_zero.sum()
print("Total available sales before replacement:", before)
print("Total after replacing NaN with zero:", after)
print("Difference:", after - before)

Total available sales before replacement: 10370000.0
Total after replacing NaN with zero: 10370000.0
Difference: 0.0


# Part 17 — Conditional Business Decisions

In [208]:
#96
conditions = [store_sales > 2800000,
              store_sales < 2400000,
              (store_sales > 2400000) & (store_sales < 2800000)]
choice = ["Excellent","Needs Improvement","Good"]

result = np.select(conditions,choice,default="Unknown")

for store, sales, label in zip(stores, store_sales, result):
  print(store, ":", sales, "->", label)

Bengaluru : 2270000 -> Needs Improvement
Hyderabad : 2295000 -> Needs Improvement
Chennai : 2310000 -> Needs Improvement
Mumbai : 2820000 -> Excellent
Pune : 1980000 -> Needs Improvement


In [209]:
#97
profits = sales_data - cost_data
conditions = [profits > 200000,
             (profits > 100000) & (profits < 200000),
             profits < 100000]
choice = ["Highly Profitable","Profitable","Low Profit"]
Profitability_Classification = np.select(conditions,choice,default="Loss")
print(Profitability_Classification)

[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


In [210]:
#98
Store_Expansion = ((store_sales > 2500000) & (store_profits > 700000)
 & (store_profit_margin > 25))
for i in stores[Store_Expansion]:
  print("Store Name:", i)

Store Name: Mumbai


In [211]:
#99
avg_category_sales = np.mean(sales_data,axis=0)
promotion_mask = np.logical_and(
    avg_category_sales < 300000,
    category_profit_margin > 25
)

print(categories[promotion_mask])

['Furniture' 'Beauty' 'Sports']


In [212]:
#100
cost_optimization = np.logical_and(
    cost_data > 250000,
    profit_margin < 25
)

rows, cols = np.where(cost_optimization)

for r, c in zip(rows, cols):
    print(
        f"Store: {stores[r]}, "
        f"Category: {categories[c]}, "
    )

Store: Bengaluru, Category: Electronics, 
Store: Hyderabad, Category: Electronics, 
Store: Hyderabad, Category: Groceries, 
Store: Chennai, Category: Electronics, 
Store: Chennai, Category: Groceries, 
Store: Mumbai, Category: Electronics, 
Store: Mumbai, Category: Groceries, 
Store: Pune, Category: Electronics, 
Store: Pune, Category: Groceries, 


# Part 18 — Inventory

In [213]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

In [214]:
#101
closing_stock = opening_stock - units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [217]:
#102
low_stock = closing_stock < 30
r, c = np.where(low_stock)
for i, j in zip(r, c):
    print(stores[i], categories[j],":", closing_stock[i, j])

Bengaluru Electronics : 25
Bengaluru Furniture : 25
Hyderabad Electronics : 25
Hyderabad Furniture : 25
Chennai Electronics : 25
Chennai Furniture : 25
Mumbai Electronics : 25
Pune Electronics : 25
Pune Furniture : 20


In [219]:
#103
stock_remaining_percentage = (closing_stock / opening_stock) * 100
print(np.round(stock_remaining_percentage, 2))

[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


In [220]:
#104
sold_percentage = (units_sold / opening_stock) * 100
fast_moving = sold_percentage > 80
r, c = np.where(fast_moving)
for i, j in zip(r, c):
    print(
        stores[i],
        categories[j],
        round(sold_percentage[i, j], 2)
    )

Bengaluru Groceries 84.44
Hyderabad Groceries 84.0
Hyderabad Clothing 82.14
Chennai Electronics 80.77
Chennai Groceries 83.33
Chennai Clothing 84.38
Mumbai Electronics 83.33
Mumbai Groceries 85.45
Mumbai Clothing 84.29
Pune Groceries 82.5


In [221]:
#105
category_units = units_sold.sum(axis=0)
for c, v in zip(categories, category_units):
    print(c, v)

Electronics 485
Groceries 1950
Clothing 1240
Furniture 345
Beauty 980
Sports 720


In [224]:
#106
store_units = units_sold.sum(axis=1)
for s, v in zip(stores, store_units):
    print(s,":", v)

Bengaluru : 1110
Hyderabad : 1175
Chennai : 1095
Mumbai : 1390
Pune : 950


In [227]:
#107
idx = np.argmax(store_units)
print(stores[idx], ":",store_units[idx])

Mumbai : 1390


In [228]:
#108
reorder_matrix = closing_stock < 25
print(reorder_matrix)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [229]:
#109
reorder_quantity = np.where(closing_stock < 25,100 - closing_stock,0)
print(reorder_quantity)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


# Part 19 — Advanced NumPy

In [230]:
#110
cumulative_store_sales = np.cumsum(sales_data,axis=1)
print(cumulative_store_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [232]:
#111
cumulative_company_sales = np.cumsum(sales_data.flatten())
print(cumulative_company_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [233]:
#112
category_differences = np.diff(sales_data,axis=1)
print(category_differences)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [234]:
#113
unique_sales, frequency = np.unique(sales_data,return_counts=True)
for value, count in zip(unique_sales, frequency):
    print(value, count)

175000 1
185000 1
190000 1
205000 1
210000 1
215000 1
225000 2
240000 1
250000 1
260000 1
275000 1
280000 1
290000 1
295000 1
310000 2
340000 1
345000 1
375000 1
390000 1
405000 1
420000 1
460000 1
510000 1
690000 1
780000 1
850000 1
920000 1
1050000 1


In [237]:
#114
row,col = np.where(sales_data == 420000)
for r,c in zip(row,col):
  print("Store:",stores[r],"Category:",categories[c])

Store: Bengaluru Category: Groceries


In [238]:
#115
profitable_mask = sales_data > cost_data
print(profitable_mask)
print("All profitable:", np.all(profitable_mask))

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
All profitable: True


In [241]:
#116
reporting_profit = np.clip(profit_data,75000,250000)
print(reporting_profit)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [242]:
#117
sales_min = sales_data.min()
sales_max = sales_data.max()
normalized_sales = ((sales_data - sales_min) /(sales_max - sales_min))
print(normalized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


In [243]:
#118
standardized_sales = ((sales_data - sales_data.mean()) /sales_data.std())
print(standardized_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [244]:
#119
margin_2dp = np.round(profit_margin, 2)
margin_whole = np.round(profit_margin)
margin_floor = np.floor(profit_margin)
margin_ceil = np.ceil(profit_margin)
print("2 decimals:\n", margin_2dp)
print("Whole:\n", margin_whole)
print("Floor:\n", margin_floor)
print("Ceiling:\n", margin_ceil)

2 decimals:
 [[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
Whole:
 [[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
Floor:
 [[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
Ceiling:
 [[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


In [245]:
#120
margin_2dp = np.round(profit_margin, 2)
margin_whole = np.round(profit_margin)
margin_floor = np.floor(profit_margin)
margin_ceil = np.ceil(profit_margin)

print("2 decimals:\n", margin_2dp)
print("Whole:\n", margin_whole)
print("Floor:\n", margin_floor)
print("Ceiling:\n", margin_ceil)

2 decimals:
 [[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
Whole:
 [[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
Floor:
 [[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
Ceiling:
 [[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


# Part 20: Final Retail Analytics Project

In [260]:
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("===================================")
print("Company Summary")
print("---------------")
print("Total sales: ",np.sum(sales_data))
print("Total cost: ",np.sum(cost_data))
print("Total profit: ",np.sum(sales_data - cost_data))
print("\n")

print("BEST-PERFORMING STORE")
print("---------------------")
store_profit = np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
Best_Performing_Index = np.argmax(store_profit)
profits = sales_data - cost_data
profits_margin = np.round((profits/sales_data) * 100,2)
print("Store: ",stores[Best_Performing_Index])
print("Sales: ",sales_data[Best_Performing_Index])
print("Cost: ",cost_data[Best_Performing_Index])
print("Profit: ",profits[Best_Performing_Index])
print("Profit Margin: ",profits_margin[Best_Performing_Index])
print("\n")

print("MOST PROFITABLE CATEGORY")
print("------------------------")
profit_cat_index = np.argmax(np.sum(profits,axis=0))
cat_profits = (np.sum(sales_data,axis=0)) - (np.sum(cost_data,axis=0))
cat_profit_margin = np.round(cat_profits/cost_data * 100,2)
print("Category: ",categories[profit_cat_index])
print("Sales: ",sales_data[profit_cat_index])
print("Cost:", cost_data[profit_cat_index])
print("Profits: ",cat_profits[profit_cat_index])
print("profit Margin: ",cat_profit_margin[profit_cat_index])
print("\n")

print("EXPANSION RECOMMENDATIONS")
print("-------------------------")
Total_sales = np.sum(sales_data,axis=1)
Total_profits = np.sum((sales_data - cost_data),axis=1)
Profit_Margin = (Total_profits/Total_sales) * 100
Eligible_Stores = ((Total_sales > 2500000) & (Total_profits > 700000) & (Profit_Margin > 25))
row = np.where(Eligible_Stores)
for r in row:
  print("Eligible Stores: ",stores[r])

print("\n")

print("COST OPTIMIZATION")
print("------------------")

profit_margin = np.round((sales_data - cost_data)/sales_data * 100,2)

COST_OPTIMIZATION = ((cost_data > 250000) & (profit_margin < 25))
row,col = np.where(COST_OPTIMIZATION)
for r, c in zip(row,col):
  print("Strore: ",stores[r])
  print("Category: ",categories[c])
  print("Cost: ",cost_data[r,c])
  print("Profit Margin: ",profit_margin[r,c],"%")

print("\n")
print("INVENTORY REORDER")
print("------------------")
Closing_Stock = opening_stock - units_sold
reorder_condition = closing_stock < 25
row,col = np.where(reorder_condition)

for r,c in zip (row,col):
  reorder_quantity = 100 - closing_stock[r,c]
  print("Store: ",stores[r])
  print("Category: ",categories[c])
  print("Closing Stock: ",closing_stock[r,c])
  print("Reorder Quantity: ",reorder_quantity)


SMARTMART RETAIL PERFORMANCE REPORT
Company Summary
---------------
Total sales:  11675000
Total cost:  8600000
Total profit:  3075000


BEST-PERFORMING STORE
---------------------
Store:  Mumbai
Sales:  [1050000  510000  375000  345000  250000  290000]
Cost:  [790000 390000 265000 250000 165000 205000]
Profit:  [260000 120000 110000  95000  85000  85000]
Profit Margin:  [24.76 23.53 29.33 27.54 34.   29.31]


MOST PROFITABLE CATEGORY
------------------------
Category:  Electronics
Sales:  [850000 420000 310000 275000 190000 225000]
Cost: [640000 315000 220000 205000 125000 160000]
Profits:  1040000
profit Margin:  [162.5  166.67 206.82 180.49 276.   212.5 ]


EXPANSION RECOMMENDATIONS
-------------------------
Eligible Stores:  ['Mumbai']


COST OPTIMIZATION
------------------
Strore:  Bengaluru
Category:  Electronics
Cost:  640000
Profit Margin:  24.71 %
Strore:  Hyderabad
Category:  Electronics
Cost:  590000
Profit Margin:  24.36 %
Strore:  Hyderabad
Category:  Groceries
Cost:  3500